name: Entrenar y Desplegar Modelo

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      retrain:
        description: 'Reentrenar modelo (yes/no)'
        required: true
        default: 'no'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Login a DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Entrenar modelo
        if: ${{ github.event.inputs.retrain == 'yes' || github.event_name == 'workflow_dispatch' }}
        run: |
          python app/models/main.py --retrain --data-path data/membership_groceries_userprofile.csv --output-path models/grocery_membership_model.joblib
        env:
          API_KEY: ${{ secrets.API_KEY }}

      - name: Construir y publicar imagen Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./app/models/
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/grocery-membership:latest,${{ secrets.DOCKER_USERNAME }}/grocery-membership:${{ github.sha }}
          build-args: |
            API_KEY=${{ secrets.API_KEY }}
