# .github/workflows/retrain_model.yml
name: Reentrenamiento de Modelo
on:
  schedule:
    - cron: '0 0 * * 0'  # Semanalmente los domingos
  workflow_dispatch:

jobs:
  retrain:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Reentrenar modelo
        run: python app/models/main.py --retrain
        env:
          API_KEY: ${{ secrets.API_KEY }}
      - name: Construir y publicar imagen Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/grocery-membership:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}